export { default as Home } from "./Home"
export { default as ProductPage } from "./Product"
export { default as ProductDetail } from "./ProductDetail"
export { default as Contact } from "./Contact"
export { default as About } from "./About"
export {default as Cart}from "./Cart"
export {default as Checkout} from "./Checkout"
export {default as Login } from "../../Auth/Pages/Login"
export {default as Register } from "../../Auth/Pages/Register"